### ISSUE TITLE
Rating buttons not showing

### ISSUE THREAD

**Issue by erolasan** [codemybrainsout/smart-app-rate#12]
I am using this configuration for the dialog:

```
 final RatingDialog ratingDialog = new RatingDialog.Builder(this)
                .threshold(3)
                .session(10)
                .title("Are you enjoying the app?")
                .titleTextColor(R.color.black)
                .positiveButtonText("Not Now")
                .negativeButtonText("Never")
                .positiveButtonTextColor(R.color.black)
                .negativeButtonTextColor(R.color.black)
                .formTitle("Submit Feedback")
                .formHint("Tell us where we can improve")
                .formSubmitText("Submit")
                .formCancelText("Cancel")
                .ratingBarColor(R.color.colorPrimary)
                .onRatingChanged(new RatingDialog.RatingDialogListener() {
                    @Override
                    public void onRatingSelected(float rating, boolean thresholdCleared) {
                        Log.d("Rating", rating + "");
                    }
                })
                .onRatingBarFormSumbit(new RatingDialog.RatingDialogFormListener() {
                    @Override
                    public void onFormSubmitted(String feedback) {
                        Log.d("Feedback", feedback + "");
                    }
                }).build();
     ratingDialog.show();
```

But the rating buttons below the rating bar are not showing and when i try to tap, there is a small line that gets focused, which i assume is the button layout. But i don't understand why its being cut off.
I tried to change the text size of the buttons, and they were still being cut off. The buttons on the feedback dialog are displaying properly though. Any ideas whats wrong?

**Comment by kr-ke** [comment]
Same for me. Seems that happens, when the title is too long. When I use the german translated text, the buttons dissappear, in English Language everything is ok.

So please fix this issue.

**Comment by ahulr** [comment]
Hi, I've fixed this issue. Please update your gradle dependency to v1.0.7

`compile 'com.codemybrainsout.rating:ratingdialog:1.0.7'`

**Comment by kr-ke** [comment]
Thank you very much!

**Comment by erolasan** [comment]
Thanks!

**Comment by neutt22** [comment]
Weird, the issue still persist on my project tho im using that version `1.0.7`
